
target 'PeopleInSpaceSwiftUI' do
    pod 'common', :path => '../../common'
    pod 'KMPNativeCoroutinesAsync', '0.13.0'
end

target 'PeopleInSpaceWidgetExtension' do
    pod 'common', :path => '../../common'
    pod 'KMPNativeCoroutinesCombine', '0.13.0'
end