
target 'PeopleInSpaceSwiftUI' do
    pod 'common', :path => '../../common'
    pod 'KMPNativeCoroutinesCombine', '0.8.0'
end

target 'PeopleInSpaceWidgetExtension' do
    pod 'common', :path => '../../common'
    pod 'KMPNativeCoroutinesCombine', '0.8.0'
end